### ISSUE TITLE
Cannot open display error

### ISSUE THREAD

**Issue by a10kiloham** [justinribeiro/dockerfiles#26]
This seemed to work a few days ago but anytime today I open a fresh container I get the error in logs
```
(google-chrome-stable:1): Gtk-WARNING **: cannot open display:
```

Ideas?
Cheers

**Comment by justinribeiro** [comment]
Normally when you get the Gtk display warning, it's when the `--headless` flag isn't passed (and the container doesn't have xvfb, hence the error). 

Nothing in that file has changed in the last week; the build on Hub looks okay (I just deleted and re-pulled and fired it up without issue).

Are you building it from the source file or pulling from Hub? What's your run command look like?

**Comment by bobbysteel** [comment]
I pulled from hub. Only change I've made is starting on local ip Only -p
127.0.0.1:9222:9222

**Comment by bobbysteel** [comment]
Really baffling - i deleted the entire image and re-pulled. The jihchi/headless-chrome works fine but this image for some reason keeps instantly throwing this error upon startup.

**Comment by bobbysteel** [comment]
Updated today and it's still happening. It's odd that the other docker image works fine but this one still throws a Gtk warning but didn't originally.

**Comment by justinribeiro** [comment]
Having a difficult time duping this. What version of docker are you running / which OS? Let me see if I can spin up a match and I'll track it down.

**Comment by bobbysteel** [comment]
Ubuntu 16.02.4 LTS

Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

It's really odd - the other headless version still works great and this one
did work for a while. There must be some sort of other conflict in the
system I installed between now and then but it's baffling how this one
doesn't start but the other one does with very similar config.

**Comment by bobbysteel** [comment]
Just updated to newer version and same issue still
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by bobbysteel** [comment]
Crap just figured out it's the --restart-always command in docker that triggers the GTK error. Super weird. Any idea why that would be? Feels like they shouldn't be related at all. Odd.
