### ISSUE TITLE
How are you controlling headless Chrome when it's running in a Docker?

### ISSUE THREAD

**Issue by vg-pulsepoint** [justinribeiro/dockerfiles#28]
Most of the tutorials use the chromedriver to control chrome, which explicitly points to the binary file. How do you programmatically control Chrome when it runs remotely in a Docker?

**Comment by caryyu** [comment]
@vg-pulsepoint  see https://hub.docker.com/r/caryyu/selenium-chrome/

**Comment by justinribeiro** [comment]
I control Chrome through the container primarily via Chrome Debugging Protocol and port 9222. I do this via https://github.com/cyrus-and/chrome-remote-interface which you can script. To show this in action, I fired up the REPL in screenshot below:

![image](https://user-images.githubusercontent.com/643503/29232887-dd2361a2-7ea2-11e7-8036-307fa486060e.png)

If you're looking for Selenium WebDriver support, @yukinying has a version (https://github.com/yukinying/chrome-headless-browser-docker) that builds on top of the official [docker-selenium}(https://github.com/SeleniumHQ/docker-selenium) image.
