### ISSUE TITLE
Request: Ability to set uid/gid of chrome user

### ISSUE THREAD

**Issue by if-kyle** [justinribeiro/dockerfiles#30]
Love the container, thanks for it!

One of the challenges I'm facing is that the uid/gid that comes out for mounted volumes does is not controllable (unless I'm missing something).

Do you have any solutions or would gosu be a good solution here?  I always hate to fork docker containers just to change uid/gid to my needs:

https://stackoverflow.com/questions/36781372/docker-using-gosu-vs-user

https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

**Comment by justinribeiro** [comment]
Realize this is rather old issue, but the userns-remap is generally the way to go to handle this at the use level. See resources such as [Isolate containers with a user namespace](https://docs.docker.com/engine/security/userns-remap/) or [Use Linux user namespaces to fix permissions in docker volumes](https://www.jujens.eu/posts/en/2017/Jul/02/docker-userns-remap/)
