### ISSUE TITLE
Lighthouse: No usable sandbox!

### ISSUE THREAD

**Issue by TAnas0** [justinribeiro/dockerfiles#47]
Hey,

Even after the changes in the pull request https://github.com/justinribeiro/dockerfiles/pull/46, the Lighthouse audit crashes with the message:
```
  ChromeLauncher Waiting for browser....................................................................................................... +503ms
  ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:43449 +3ms
  ChromeLauncher:error Logging contents of /tmp/lighthouse.5V3TSDY/chrome-err.log +2ms
  ChromeLauncher:error [0316/163340.738658:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
  ChromeLauncher:error Failed to generate minidump. +1ms
Unable to connect to Chrome
```

Also, note that it runs successfully with the Chrome option `--no-sandbox`:
```bash
lighthouse --chrome-flags="--headless --disable-gpu --no-sandbox" https://example.com
```

[Puppeteer's README](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox) suggests some changes to solve the error

Would that be of interest to you? Knowing that, apparently there is official support for Docker from the Lighthouse team as discussed in here https://github.com/GoogleChrome/lighthouse/issues/3715

**Comment by justinribeiro** [comment]
I'm not a fan of using `--no-sandbox` (I consider it an effort of last resort). If you run with Jess' SECCOMP profile, you don't need to disable the sandbox.

In terms of the upstream, I've discussed this with the Lighthouse folks previously in 5962. There is other ongoing work that I hope comes to fruition.
