### ISSUE TITLE
Setting --proxy-server

### ISSUE THREAD

**Issue by gogo9th** [justinribeiro/dockerfiles#48]
Hi,

Thanks very much for your very useful chrome-headless docker container. I am trying to set up a chrome container that uses my local web proxy. However, I am not sure how to set the "--proxy-server" argument value for the chrome-headless container... Is it ever supported? If so, I would really appreciate your feedback.

**Comment by chrbala** [comment]
I've been building my own images with the arguments I need, but it would be great if these images supported arbitrary arguments!

**Comment by justinribeiro** [comment]
The chrome-headless containers have CMD and ENTRYPOINT, which will allow you to add arbitrary arguments without custom builds:

![image](https://user-images.githubusercontent.com/643503/73466124-46013280-4336-11ea-941d-7297dcb71b70.png)

**Comment by gogo9th** [comment]
Hi, thanks very much for your answer. I tried the following:

docker run -it -p 9222:9222 --cap-add=SYS_ADMIN justinribeiro/chrome-headless "--proxy-server=64.227.8.188:8181"

but I get the error:

(google-chrome:1): Gtk-WARNING **: 07:47:48.668: cannot open display:

Do you have any idea how I could fix it...?

**Comment by gogo9th** [comment]
Actually, even if I run the following:

docker run -it -p 9222:9222 --cap-add=SYS_ADMIN justinribeiro/chrome-headless "--proxy-server=64.227.8.188:8181" "--headless"

the container exits immediately.

**Comment by justinribeiro** [comment]
I should have been more clear: the docker documentation explains the process fully[Overriding Dockerfile image defaults](https://docs.docker.com/engine/reference/run/#overriding-dockerfile-image-defaults).

As an example, here's the container running with the full set of flags required in a pure override: 

![image](https://user-images.githubusercontent.com/643503/73762552-34000500-4725-11ea-9fe3-46133a33a0c9.png)

**Comment by gogo9th** [comment]
Thanks very much for your guide, now it works fine! 

In fact, I have one last question. I wonder if you know how we can add trusted certificates. I don't see a command line option for adding a certificate:
[](https://peter.sh/experiments/chromium-command-line-switches/)

For me, using a certificate is important rather than adding simply adding the "--ignore-certificate-errors --ignore-certificate-errors-spki-list" options, because otherwise Chrome doesn't cache fetched resources (as they are untrusted)...

**Comment by justinribeiro** [comment]
The container doesn't have a means to consume custom certificates; you'd have to build your own hook to import them into the trust. If you've generated a certificate for say a local server, you can use certutil to do this on linux with something along the lines of:

```
$ certutil -d sql:$HOME/.pki/nssdb -A -t \"P,,\" -n ./my-local-cert.pem -i  ./my-local-cert.pem"
```

**Comment by gogo9th** [comment]
I actually knew about this command, but never imagined using it inside a container to get around this issue. Thanks very much for your tip, again!
