### ISSUE TITLE
can I run lighthouse without mounting local filesystem

### ISSUE THREAD

**Issue by ashwin31** [justinribeiro/dockerfiles#54]
![Screenshot from 2020-07-02 13-44-24](https://user-images.githubusercontent.com/365610/86333940-33cf4b80-bc6a-11ea-9ca8-c2b988c7db0a.png)

I did run without mounting local file system.

**Comment by justinribeiro** [comment]
Yes, you should be able to run within the interactive container. What OS / docker version?

**Comment by ashwin31** [comment]
@justinribeiro 
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

Docker version 19.03.12, build 48a66213fe

**Comment by ashwin31** [comment]
I ran like this
```
docker run -itv  --cap-add=SYS_ADMIN justinribeiro/lighthouse
```
because I don't want to use local filesystem. My end goal is to move this container to kebernetes if it's working.

**Comment by justinribeiro** [comment]
Humm, runs clean for me in that env setup you noted.

```bash
docker run --rm -it --cap-add SYS_ADMIN justinribeiro/lighthouse
```

![image](https://user-images.githubusercontent.com/643503/86420136-7a34a280-bc8a-11ea-9762-6a0c04368fc6.png)

**Comment by ashwin31** [comment]
@justinribeiro thank you for your response. It worked like charm.

just two commands
```
docker run --rm -it --cap-add SYS_ADMIN justinribeiro/lighthouse
lighthouse --quiet --chrome-flags="--headless --disable-gpu" https://justinribeiro.com
```
I don't know why it was not working earlier.

Thank you very much for your support.
